# Generated by Django 6.0.6 on 2026-06-22 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='currency',
            field=models.CharField(choices=[('BRL', 'BRL (R$)'), ('USD', 'USD ($)')], default='BRL', max_length=3),
        ),
    ]
